
#import dependencies
import media
import fresh_tomatoes

#creating movie instance
#For creating a movie instance you need to pass four arguments to the function Movie that in media where it will have the class defined
frozen = media.Movie("Frozen","When their kingdom becomes trapped in perpetual winter, fearless Anna (Kristen Bell) joins forces with mountaineer Kristoff (Jonathan Groff) and his reindeer sidekick to find Anna's sister, Snow Queen Elsa (Idina Menzel), and break her icy spell. Although their epic journey leads them to encounters with mystical trolls, a comedic snowman (Josh Gad), harsh conditions, and magic at every turn, Anna and Kristoff bravely push onward in a race to save their kingdom from winter's cold grip.","http://img2.wikia.nocookie.net/__cb20131010215010/disney/images/b/b1/Frozen_ver8_xlg.jpg%3F9d7bd4.jpg","https://www.youtube.com/watch?v=R-cdIvgBCWY")
diaryofwimpykid = media.Movie("Diary of the wimpy kid","Middle school is not an enjoyable experience for preteen Greg Heffley (Zachary Gordon) but a horrid ordeal of social land-mines that he must bear. To do so, he devises schemes to win him the recognition and status he feels he deserves -- all of which fail miserably. Greg chronicles his misadventures, thoughts and opinions in a diary to prepare for the day that he will no longer have to put up with nonsense.", "http://upload.wikimedia.org/wikipedia/en/4/4e/Diary_of_a_Wimpy_Kid_movie_poster.jpg","https://www.youtube.com/watch?v=ZbqqYuG1TCM")
homealone = media.Movie("Home Alone","When bratty 8-year-old Kevin McCallister (Macaulay Culkin) acts out the night before a family trip to Paris, his mother (Catherine O'Hara) makes him sleep in the attic. After the McCallisters mistakenly leave for the airport without Kevin, he awakens to an empty house and assumes his wish to have no family has come true. But his excitement sours when he realizes that two con men (Joe Pesci, Daniel Stern) plan to rob the McCallister residence, and that he alone must protect the family home","http://ia.media-imdb.com/images/M/MV5BMTUzMzg4MTg2M15BMl5BanBnXkFtZTYwNDM4OTk4._V1_SX640_SY720_.jpg","https://www.youtube.com/watch?v=CK2Btk6Ybm0")
homealone2 = media.Movie("Home Alone 2","After snarky youth Kevin McCallister (Macaulay Culkin) loses track of his father at the airport, he mistakenly gets on a plane headed for New York City -- while the rest of the McCallisters fly to Florida. Now alone in the Big Apple, Kevin cons his way into a room at the Plaza Hotel and begins his usual antics. But when Kevin discovers that the Sticky Bandits (Joe Pesci, Daniel Stern) are on the loose, he struggles to stop them from robbing an elderly man's toy store just before Christmas.","https://image.tmdb.org/t/p/original/gCWsYFfQLinyjndca8LbQP49qtC.jpg","https://www.youtube.com/watch?v=vIRoNlPZeqk")
homealone3 = media.Movie("Home Alone 3","When an inept group of criminals tries to get a stolen top-secret computer chip through airport security, it ends up in a toy car in the luggage of the elderly Mrs. Hess (Marian Seldes). Unable to promptly retrieve the chip, the felons follow Hess and the car to her neighborhood. After she gives the toy to young Alex Pruitt (Alex D. Linz), who is home sick from school, he becomes the target of the criminals. However, the precocious kid is on to their schemes and ready to fight the thieves off.","http://ia.media-imdb.com/images/M/MV5BOTAxODU4NjAxN15BMl5BanBnXkFtZTcwOTg4MjU1MQ@@._V1_SX640_SY720_.jpg","https://www.youtube.com/watch?v=CK0j5OMApkw")
honeyishrunkthekids = media.Movie("Honey I shrunk the kids","When kids sneak into inventor Wayne Szalinski's (Rick Moranis) upstairs lab to retrieve an errant baseball, his experimental shrink ray miniaturizes them. When Szalinski returns home, he destroys the device -- which he thinks is a failure -- and dumps it in the trash, throwing out the kids along with it. The four children, now 1/4-inch tall, must survive the journey back to the house through a yard where sprinklers bring treacherous storms and garden-variety ants stampede like elephants.","http://ia.media-imdb.com/images/M/MV5BMTcxMDYyOTQ3M15BMl5BanBnXkFtZTYwNjc5NzI5._V1_SX640_SY720_.jpg","https://www.youtube.com/watch?v=U68aYI5LhvM")
jumanji = media.Movie("Jumanji","A magical board game unleashes a world of adventure on siblings Peter (Bradley Pierce) and Judy Shepherd (Kirsten Dunst). While exploring an old mansion, the youngsters find a curious, jungle-themed game called Jumanji in the attic. When they start playing, they free Alan Parrish (Robin Williams), who's been stuck in the game's inner world for decades. If they win Jumanji, the kids can free Alan for good -- but that means braving giant bugs, ill-mannered monkeys and even stampeding rhinos!","http://upload.wikimedia.org/wikipedia/en/b/b6/Jumanji_poster.jpg","https://www.youtube.com/watch?v=OJKHQLM8AbM")


#creating list of movies
movie_list = [frozen,diaryofwimpykid,homealone,homealone2,homealone3,honeyishrunkthekids,jumanji]

#this is the place where we send all the movies list and and in fresh_tomatoes is the python file where it displays as a image
fresh_tomatoes.open_movies_page(movie_list)
